apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-apps.fullname" . }}-consumer
  labels:
    app: consumer
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.consumer.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: consumer
