image:
  repository: chaos-monkey
  tag: latest
  pullPolicy: Always

controller:
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

daemon:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metricsPort: 8080

nodeSelector: {}
tolerations: []
affinity: {}
