apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-controller
  labels:
    app: {{ include "chaos-monkey.fullname" . }}-controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chaos-monkey.fullname" . }}-controller
  template:
    metadata:
      labels:
        app: {{ include "chaos-monkey.fullname" . }}-controller
    spec:
      serviceAccountName: {{ include "chaos-monkey.fullname" . }}-controller
      containers:
        - name: chaos-monkey-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/app/chaos-monkey"
          args:
            - "-mode=controller"
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
