apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-broker
  namespace: kafka
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: strimzi.io/kind
        operator: In
        values:
          - Kafka
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      interval: 15s
      path: /metrics
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: kubernetes_pod_name
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node_name
