apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: schema-registry
  namespace: kafka
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: confluent-sr
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
    - targetPort: 8081
      interval: 15s
      path: /metrics
