apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-apps.fullname" . }}-consumer
  labels:
    app: consumer
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.consumer.metricsPort }}
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.kafka.bootstrapServers }}
            - name: TOPIC
              value: {{ .Values.kafka.topic }}
            - name: GROUP_ID
              value: {{ .Values.consumer.groupId }}
            - name: SCHEMA_REGISTRY_URL
              value: {{ .Values.kafka.schemaRegistryUrl }}
            - name: METRICS_PORT
              value: "{{ .Values.consumer.metricsPort }}"
