apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-controller
  labels:
    app: {{ include "chaos-monkey.fullname" . }}-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-daemon
  labels:
    app: {{ include "chaos-monkey.fullname" . }}-daemon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-controller
rules:
  - apiGroups: ["chaos.dk1027.io"]
    resources: ["chaosexperiments", "chaosexperiments/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["chaos.dk1027.io"]
    resources: ["nodechaostasks", "nodechaostasks/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "chaos-monkey.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "chaos-monkey.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-daemon
rules:
  - apiGroups: ["chaos.dk1027.io"]
    resources: ["nodechaostasks"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chaos-monkey.fullname" . }}-daemon
subjects:
  - kind: ServiceAccount
    name: {{ include "chaos-monkey.fullname" . }}-daemon
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "chaos-monkey.fullname" . }}-daemon
  apiGroup: rbac.authorization.k8s.io
